"""Configuration management."""

from pathlib import Path

from .output import die, log_step, log_success
from .github import validate_github_repo


def load_config(config_path: Path) -> dict[str, str]:
    """Load configuration from config.env file."""
    if not config_path.exists():
        return {}

    config = {}
    with open(config_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                config[key.strip()] = value.strip()
    return config


def prompt_config(config_path: Path) -> None:
    """Interactively prompt for configuration."""
    config_path.parent.mkdir(parents=True, exist_ok=True)

    print("yolo-cage configuration")
    print()

    github_pat = input("GitHub PAT: ").strip()
    if not github_pat:
        die("GitHub PAT is required")

    repo_url = input("Repository URL: ").strip()
    if not repo_url:
        die("Repository URL is required")

    # Validate repository access before continuing
    log_step("Validating repository access...")
    valid, message = validate_github_repo(repo_url, github_pat)
    if not valid:
        die(message)
    log_success(message)
    print()

    git_name = input("Git name [yolo-cage]: ").strip() or "yolo-cage"
    git_email = input("Git email [yolo-cage@localhost]: ").strip() or "yolo-cage@localhost"
    proxy_bypass = input("Proxy bypass domains (optional, comma-separated): ").strip()

    with open(config_path, "w") as f:
        f.write("# yolo-cage configuration\n")
        f.write("# Generated by yolo-cage build --interactive\n\n")
        f.write("# Required\n")
        f.write(f"GITHUB_PAT={github_pat}\n")
        f.write(f"REPO_URL={repo_url}\n\n")
        f.write("# Git identity\n")
        f.write(f"GIT_NAME={git_name}\n")
        f.write(f"GIT_EMAIL={git_email}\n")

        if proxy_bypass:
            f.write(f"\nPROXY_BYPASS={proxy_bypass}\n")

    log_success(f"Config written to {config_path}")
